### ISSUE TITLE
IEXAuthenticationError when using new version of IEX API

### ISSUE THREAD

**Issue by w601sxs** [addisonlynch/iex-examples#2]
I get an IEXAuthenticationError when I do the following -

    batch = Stock(portfolio, token = "<my_secret_token_from_iex_cloud>") 
     
    current_prices = batch.get_price() 
    historical_prices = batch.get_chart(range = '1d') 

Same issue when I use the publishable token. What am I doing wrong?

**Comment by gabrielfior** [comment]
I also got the same problem when using version 0.4.2.

```python
from iexfinance.stocks import Stock
a = Stock("ITUB")
a.get_price()
```
```
    176                 raise auth_error(auth_msg)
    177             else:
--> 178                 raise IEXQueryError("The query could not be completed. "
    179                                     "There was a client-side error with your "
    180                                     "request.")

IEXQueryError: An error occurred while making the query.
```

**Comment by gabrielfior** [comment]
Update - I just noticed I entered my API credentials wrongly.

In a Jupyter notebook:
```python
%env IEX_TOKEN='<my-secret-toke>'
```

The way that it worked for me was:
```python
%env IEX_TOKEN=<my-secret-toke>
```
